{
 "title": "Chia Farm Dashboard",
 "description": "Displays all important metrics from your Chia farming node and all connected harvesters, collected by the official chia-exporter. This dashboard is based on the great work made by philippnormann (https://grafana.com/grafana/dashboards/14544)",
 "tags": [ "chia" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "PlotType",
    "query": {
     "query": "label_values(chia_farmer_plot_filesize, type)"
    }
   },
   {
    "name": "HarvesterId",
    "label": "Harvester Id",
    "query": {
     "query": "label_values(chia_farmer_plot_filesize,exported_node_id)"
    }
   },
   { "name": "PriceCurrency", "label": "Currency", "query": { "query": "metrics(chia_price_.*)" } },
   {
    "name": "PriceCorrectionFactor",
    "query": "btc : 100000000, eth : 1000000000, eur : 100, usd : 100"
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Status",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_full_node_node_synced)"
    }
   ]
  },
  {
   "title": "Plot Size Delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(chia_farmer_plot_filesize{type=\"$PlotType\"})"
    }
   ]
  },
  {
   "title": "Plot Count Delta",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(chia_farmer_plot_count{type=\"$PlotType\"})"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "XCH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(fingerprint) ((chia_wallet_confirmed_balance{wallet_type=\"0\"})/1e12)",
     "legendFormat": "Wallet {{ fingerprint }}"
    }
   ]
  },
  {
   "title": "Blocks Found",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(chia_farmer_proofs_found[$__range]))",
     "legendFormat": "Blocks Found"
    }
   ]
  },
  {
   "title": "Points Success Rate 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_pool_points_acknowledged_24h{url=\"$Pool\"} / chia_pool_points_found_24h{url=\"$Pool\"}+SL",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Full Node Peers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_full_node_connection_count{node_type=\"full_node\"})"
    }
   ]
  },
  {
   "title": "Farmer Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_full_node_connection_count{node_type=\"farmer\"})"
    }
   ]
  },
  {
   "title": "Wallet Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_full_node_connection_count{node_type=\"wallet\"})"
    }
   ]
  },
  {
   "title": "Plot Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_farmer_plot_filesize{type=\"$PlotType\"})",
     "legendFormat": "Plot Size"
    }
   ]
  },
  {
   "title": "Plot Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_farmer_plot_count{type=\"$PlotType\"})",
     "legendFormat": "Plot Count"
    }
   ]
  },
  {
   "title": "Expected Time To Win",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "18.75 / ( ( \r\n\t  ( sum(chia_farmer_plot_filesize{compression=\"1\"})  * (101.3/(1*-1.6+85.5)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"2\"})  * (101.3/(2*-1.6+85.5)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"3\"})  * (101.3/(3*-1.6+85.5)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"4\"})  * (101.3/(4*-1.6+85.5)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"5\"})  * (101.3/(5*-1.6+85.5)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"6\"})  * (101.3/(6*-1.6+85.5)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"7\"})  * (101.3/(7*-1.6+85.5)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"8\"})  * (101.3/(8*-3.1+96.0)) or vector(0) )\r\n\t+ ( sum(chia_farmer_plot_filesize{compression=\"9\"})  * (101.3/(9*-3.1+96.0)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"11\"}) * (101.3/(11*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"12\"}) * (101.3/(12*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"13\"}) * (101.3/(13*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"14\"}) * (101.3/(14*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"15\"}) * (101.3/(15*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"16\"}) * (101.3/(16*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"17\"}) * (101.3/(17*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"18\"}) * (101.3/(18*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"19\"}) * (101.3/(19*-3.7+127)) or vector(0) )\r\n    + ( sum(chia_farmer_plot_filesize{compression=\"20\"}) * (101.3/(20*-3.7+127)) or vector(0) )\r\n) / (sum(chia_full_node_netspace_mib)*1048576)\r\n)"
    }
   ]
  },
  {
   "title": "Points Found 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "points" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(chia_farmer_points_acknowledged_since_start[24h])+SL",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "Node Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_full_node_node_height)",
     "legendFormat": "Height"
    }
   ]
  },
  {
   "title": "Blockchain DB Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_full_node_database_filesize)",
     "legendFormat": "Blockchain database size"
    }
   ]
  },
  {
   "title": "Blockchain DB Growth Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_full_node_database_filesize[$__range]))",
     "legendFormat": "Blockchain Database Growth Rate"
    }
   ]
  },
  {
   "title": "Points Acknowledged 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "points" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_farmer_points_acknowledged_since_start[24h]))",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "Signage Points",
   "type": "bargauge",
   "description": "Target 6.4 SPs per minute, 1 SP should occur every 9.375s",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(chia_full_node_total_signage_points[5m]) * 60)",
     "legendFormat": "Challanges"
    }
   ]
  },
  {
   "title": "Plot Size Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (exported_node_id,size,compression) (chia_farmer_plot_filesize{type=\"$PlotType\",exported_node_id=~\"$HarvesterId\"})",
     "legendFormat": "k{{ size }}-c{{ compression }} / {{ exported_node_id }}"
    }
   ]
  },
  {
   "title": "Chia Network Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(chia_full_node_netspace_mib)",
     "legendFormat": "Netspace"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(chia_full_node_difficulty)", "legendFormat": "Difficulty" }
   ]
  },
  {
   "title": "Proofs Found 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "proof" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_farmer_submitted_partials[24h]))",
     "legendFormat": "Submitted partials"
    }
   ]
  },
  {
   "title": "Current Points",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(chia_farmer_points_acknowledged_since_start)",
     "legendFormat": "Points"
    }
   ]
  },
  {
   "title": "Pool Difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(chia_farmer_current_difficulty)",
     "legendFormat": "Difficulty"
    }
   ]
  },
  {
   "title": "Pool Errors 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_num_pool_errors_24h{url=\"$Pool\"}+SL"
    }
   ]
  },
  {
   "title": "Filters Passed",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(chia_farmer_total_eligible_plots[5m])) * 60",
     "legendFormat": "Filters Passed"
    }
   ]
  },
  {
   "title": "Challenges",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(chia_block_challenges_total[5m]) * 60+SL",
     "legendFormat": "Challenges"
    }
   ]
  },
  {
   "title": "Plot Count Per Harvester",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "plots" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (exported_node_id,size,compression) (chia_farmer_plot_count{type=\"$PlotType\",exported_node_id=~\"$HarvesterId\"})",
     "legendFormat": "k{{ size }}-c{{ compression }} / {{ exported_node_id }}"
    }
   ]
  },
  {
   "title": "Mempool Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(chia_full_node_mempool_size)",
     "legendFormat": "Mempool Size"
    }
   ]
  },
  {
   "title": "Mempool Capacity Used",
   "type": "stat",
   "description": "Once the mempool is full (100%), a fee is required to kick other lower fee transactions out to get your transaction included in the mempool.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(chia_full_node_mempool_cost)/550000000000",
     "legendFormat": "Mempool Cost"
    }
   ]
  },
  {
   "title": "XCH Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg({__name__=~\"$PriceCurrency\"})/($PriceCorrectionFactor)",
     "legendFormat": "XCH Price"
    }
   ]
  },
  {
   "title": "Total Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(fingerprint) (avg({__name__=~\"$PriceCurrency\"})/($PriceCorrectionFactor) * (sum(chia_wallet_confirmed_balance{wallet_type=\"0\"})/1e12))",
     "legendFormat": "Wallet {{ fingerprint }}"
    }
   ]
  },
  {
   "title": "Proofs Found",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(chia_farmer_submitted_partials[1h]) * 60)",
     "legendFormat": "Proofs"
    }
   ]
  },
  {
   "title": "Harvester Lookup Times (P99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (exported_node_id) (quantile_over_time(0.99, chia_farmer_last_lookup_time{exported_node_id=~\"$HarvesterId\"}[$__rate_interval]))",
     "legendFormat": "{{ exported_node_id }}"
    }
   ]
  },
  {
   "title": "Block Validation Times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(chia_full_node_validation_time)",
     "legendFormat": "Block Validation Time"
    },
    {
     "expr": "avg(chia_full_node_pre_validation_time)",
     "legendFormat": "Pre-validation Time"
    }
   ]
  }
 ]
}